"""Export a calibrated capture volume to an animated Blender scene.

Generates one self-contained Blender Python script (bpy + numpy only, both
ship with Blender) embedding all scene data as literals, then runs Blender
headless to produce the .blend when Blender is on PATH.

The scene duplicates the visual-verification experience of the widget
explorer, in Blender: animated keypoint dots colored by wireframe segment,
the skeleton edges riding the same shape keys, every posed camera at its
world pose with its source footage as a frame-synced camera background
(numpad 0 through a camera shows the skeleton riding the subject), and a
wireframe floor grid at Z=0.

Scene frames are sync indices. Keypoint shape keys are keyframed at their
actual sync index with constant interpolation, so sparse extractions
(frame_step > 1) hold pose between samples while the footage plays every
frame in sync.

Caliscope stores world-to-camera extrinsics (OpenCV convention). The Blender
camera pose is E @ F where E carries rotation.T and the camera center
-R.T @ t, and F = diag(1, -1, -1, 1) flips Blender camera axes to OpenCV.
"""

from __future__ import annotations

import json
import logging
import shutil
import subprocess
from collections.abc import Mapping
from pathlib import Path

import numpy as np

from caliscope.cameras.camera_array import CameraArray
from caliscope.core.point_data import STATIC_SYNC_INDEX, WorldPoints
from caliscope.tracker import WireFrameView

logger = logging.getLogger(__name__)

KEYPOINT_RADIUS_M = 0.025
FLOOR_SIZE_M = 8.0

_SEGMENT_COLOR_RGB = {
    "r": (0.90, 0.20, 0.20),
    "g": (0.20, 0.80, 0.30),
    "b": (0.25, 0.45, 0.95),
    "c": (0.20, 0.80, 0.85),
    "m": (0.85, 0.30, 0.85),
    "y": (0.90, 0.85, 0.20),
    "k": (0.15, 0.15, 0.15),
    "w": (0.90, 0.90, 0.90),
}
_UNGROUPED_COLOR_RGB = (0.65, 0.65, 0.65)

_SCENE_TEMPLATE = '''"""Capture volume scene, generated by caliscope.export.write_blender_scene.

Self-contained: run with  blender --background --python {script_name}
Saves {blend_name} beside this file.
"""

import json
import os
from pathlib import Path

import bpy
import numpy as np
from mathutils import Matrix

PAYLOAD = json.loads(r"""
{payload_json}
""")


def make_material(name, color):
    mat = bpy.data.materials.new(name)
    mat.diffuse_color = (*color, 1.0)
    mat.use_nodes = True
    bsdf = mat.node_tree.nodes.get("Principled BSDF")
    bsdf.inputs["Base Color"].default_value = (*color, 1.0)
    return mat


def points_node_group(name, radius, material):
    """A Mesh-to-Points node group so bare vertices render as dots."""
    group = bpy.data.node_groups.new(name, "GeometryNodeTree")
    group.interface.new_socket("Geometry", in_out="INPUT", socket_type="NodeSocketGeometry")
    group.interface.new_socket("Geometry", in_out="OUTPUT", socket_type="NodeSocketGeometry")
    nodes, links = group.nodes, group.links
    group_in = nodes.new("NodeGroupInput")
    to_points = nodes.new("GeometryNodeMeshToPoints")
    to_points.inputs["Radius"].default_value = radius
    set_material = nodes.new("GeometryNodeSetMaterial")
    set_material.inputs["Material"].default_value = material
    group_out = nodes.new("NodeGroupOutput")
    links.new(group_in.outputs["Geometry"], to_points.inputs["Mesh"])
    links.new(to_points.outputs["Points"], set_material.inputs["Geometry"])
    links.new(set_material.outputs["Geometry"], group_out.inputs["Geometry"])
    return group


def build_mesh_object(name, vertices_first, edges):
    mesh = bpy.data.meshes.new(name)
    mesh.from_pydata([tuple(v) for v in vertices_first], [tuple(e) for e in edges], [])
    mesh.update()
    obj = bpy.data.objects.new(name, mesh)
    bpy.context.scene.collection.objects.link(obj)
    return obj


def animate_shape_keys_at(obj, vertices, frames):
    """One absolute pose per sample, keyframed exclusively at its sync index.

    Each key holds one sample's vertex positions. Keys are keyframed to 1.0 at
    their own frame and 0.0 at neighboring sample frames, with constant
    interpolation, so the active key reproduces its sample exactly and the pose
    holds between sparse samples. The keys live in the .blend; no external cache.
    """
    # Interpolation is set via the new-keyframe preference: legacy
    # Action.fcurves access is gone in Blender 5.x (layered actions).
    prefs = bpy.context.preferences.edit
    previous_interpolation = prefs.keyframe_new_interpolation_type
    prefs.keyframe_new_interpolation_type = "CONSTANT"
    obj.shape_key_add(name="Basis")
    keys = []
    for frame, verts in zip(frames, vertices):
        key = obj.shape_key_add(name=f"f_{{frame:05d}}")
        key.data.foreach_set("co", np.asarray(verts, dtype=np.float32).reshape(-1))
        keys.append(key)
    for i, (key, frame) in enumerate(zip(keys, frames)):
        if i > 0:
            key.value = 0.0
            key.keyframe_insert("value", frame=frames[i - 1])
        key.value = 1.0
        key.keyframe_insert("value", frame=frame)
        if i + 1 < len(frames):
            key.value = 0.0
            key.keyframe_insert("value", frame=frames[i + 1])
    prefs.keyframe_new_interpolation_type = previous_interpolation


def build_camera(name, width, focal_px, camera_matrix):
    """The verified OpenCV-matching recipe: sensor width in px units, lens in px."""
    cam_data = bpy.data.cameras.new(name)
    cam_data.sensor_fit = "HORIZONTAL"
    cam_data.sensor_width = float(width)
    cam_data.lens = float(focal_px)
    cam_data.shift_x = 0.0
    cam_data.shift_y = 0.0
    cam = bpy.data.objects.new(name, cam_data)
    bpy.context.scene.collection.objects.link(cam)
    cam.matrix_world = Matrix(camera_matrix)
    return cam


def add_footage_background(cam, video_path, blend_dir):
    """The source footage on the camera background, behind the geometry.

    Scene frames are sync indices, which for these clips are 0-based video
    frames; clip frame 1 (first video frame) lands on scene frame 0.
    """
    cam_data = cam.data
    cam_data.show_background_images = True
    clip = bpy.data.movieclips.load(str(video_path))
    clip.frame_start = 0
    background = cam_data.background_images.new()
    background.source = "MOVIE_CLIP"
    background.clip = clip
    background.display_depth = "BACK"
    background.frame_method = "FIT"
    background.alpha = 1.0
    clip.filepath = "//" + os.path.relpath(str(video_path), str(blend_dir))


def main():
    bpy.ops.wm.read_factory_settings(use_empty=True)
    scene = bpy.context.scene
    frames = PAYLOAD["frames"]
    scene.frame_start = frames[0]
    scene.frame_end = frames[-1]
    first = PAYLOAD["cameras"][0]
    scene.render.resolution_x = int(first["width"])
    scene.render.resolution_y = int(first["height"])

    for group in PAYLOAD["groups"]:
        obj = build_mesh_object(f"keypoints_{{group['name']}}", group["positions"][0], [])
        animate_shape_keys_at(obj, group["positions"], frames)
        material = make_material(f"keypoints_{{group['name']}}_mat", group["color"])
        node_group = points_node_group(f"dots_{{group['name']}}", PAYLOAD["keypoint_radius_m"], material)
        modifier = obj.modifiers.new("dots", "NODES")
        modifier.node_group = node_group

    if PAYLOAD["edges"]:
        skeleton = build_mesh_object("skeleton_edges", PAYLOAD["joints"][0], PAYLOAD["edges"])
        animate_shape_keys_at(skeleton, PAYLOAD["joints"], frames)
        skeleton.display_type = "WIRE"
        skeleton.show_in_front = True

    blend_path = Path(__file__).resolve().parent / "{blend_name}"
    first_camera = None
    for cam in PAYLOAD["cameras"]:
        camera = build_camera(cam["name"], cam["width"], cam["focal_px"], cam["matrix"])
        if cam.get("video"):
            add_footage_background(camera, cam["video"], blend_path.parent)
        if first_camera is None:
            first_camera = camera
    scene.camera = first_camera

    bpy.ops.mesh.primitive_grid_add(
        x_subdivisions=16, y_subdivisions=16, size=PAYLOAD["floor_size_m"], location=(0, 0, 0)
    )
    floor = bpy.context.active_object
    floor.name = "floor_z0"
    floor.display_type = "WIRE"

    bpy.ops.wm.save_as_mainfile(filepath=str(blend_path))
    print(
        f"Saved {{blend_path}}: {{len(PAYLOAD['cameras'])}} cameras, "
        f"{{len(PAYLOAD['groups'])}} keypoint groups, {{len(frames)}} sample frames"
    )


main()
'''


def _blender_camera_matrix(rotation: np.ndarray, translation: np.ndarray) -> np.ndarray:
    """The Blender camera world matrix for a caliscope world-to-camera pose."""
    extrinsic = np.eye(4)
    extrinsic[:3, :3] = rotation.T
    extrinsic[:3, 3] = -rotation.T @ translation
    flip = np.diag([1.0, -1.0, -1.0, 1.0])
    return extrinsic @ flip


def _keypoint_trajectories(world_points: WorldPoints) -> tuple[list[int], list[int], np.ndarray]:
    """Pivot world points to (frames, keypoint_ids, positions[F, K, 3]).

    Uses the object_id with the most observations when several are present.
    Gaps are held at the nearest observed sample (display only; the source
    CSV stays honest). Keypoints never observed are dropped.
    """
    df = world_points.df
    df = df[df["sync_index"] != STATIC_SYNC_INDEX]
    if df.empty:
        raise ValueError("WorldPoints contains no dynamic observations to export.")

    object_counts = df["object_id"].value_counts()
    if len(object_counts) > 1:
        logger.warning(f"Multiple object_ids {list(object_counts.index)}; exporting the most observed.")
    df = df[df["object_id"] == object_counts.idxmax()]

    frames = sorted(int(s) for s in df["sync_index"].unique())
    keypoint_ids = sorted(int(k) for k in df["keypoint_id"].unique())
    frame_pos = {f: i for i, f in enumerate(frames)}
    keypoint_pos = {k: i for i, k in enumerate(keypoint_ids)}

    positions = np.full((len(frames), len(keypoint_ids), 3), np.nan)
    rows = df["sync_index"].map(frame_pos).to_numpy()
    cols = df["keypoint_id"].map(keypoint_pos).to_numpy()
    positions[rows, cols] = df[["x_coord", "y_coord", "z_coord"]].to_numpy()

    # Hold gaps at the nearest observed sample: forward fill, then backward.
    for k in range(positions.shape[1]):
        observed = ~np.isnan(positions[:, k, 0])
        if not observed.any():
            continue
        indices = np.where(observed, np.arange(len(frames)), 0)
        np.maximum.accumulate(indices, out=indices)
        positions[:, k] = positions[indices, k]
        first_observed = int(np.argmax(observed))
        positions[:first_observed, k] = positions[first_observed, k]

    return frames, keypoint_ids, positions


def _color_groups(keypoint_ids: list[int], wireframe: WireFrameView | None) -> tuple[list[dict], list[list[int]]]:
    """Group keypoint columns by wireframe segment color; edges as column pairs."""
    keypoint_pos = {k: i for i, k in enumerate(keypoint_ids)}
    column_color: dict[int, str] = {}
    edges: list[list[int]] = []
    if wireframe is not None:
        for segment in wireframe.segments:
            id_a = wireframe.point_names.get(segment.point_A)
            id_b = wireframe.point_names.get(segment.point_B)
            if id_a not in keypoint_pos or id_b not in keypoint_pos:
                continue
            edges.append([keypoint_pos[id_a], keypoint_pos[id_b]])
            for keypoint_id in (id_a, id_b):
                column_color.setdefault(keypoint_pos[keypoint_id], segment.color)

    groups: dict[str, list[int]] = {}
    for column in range(len(keypoint_ids)):
        groups.setdefault(column_color.get(column, "ungrouped"), []).append(column)

    group_specs = []
    for color, columns in groups.items():
        rgb = _SEGMENT_COLOR_RGB.get(color, _UNGROUPED_COLOR_RGB)
        group_specs.append({"name": color, "columns": columns, "color": list(rgb)})
    return group_specs, edges


def write_blender_scene(
    camera_array: CameraArray,
    world_points: WorldPoints,
    output_path: Path | str,
    *,
    videos: Mapping[int, Path | str] | None = None,
    wireframe: WireFrameView | None = None,
    run_blender: bool = True,
) -> Path:
    """Write a self-contained Blender scene script and build the .blend.

    Args:
        camera_array: Calibrated cameras; posed cameras are exported.
        world_points: Triangulated keypoints to animate (scene frames are
            sync indices, so pass full-frame triangulations for smooth playback).
        output_path: Path for the generated scene script (.py). The .blend is
            saved beside it with the same stem.
        videos: Optional cam_id to video path mapping; matching cameras get
            their footage as a frame-synced camera background.
        wireframe: Optional skeleton topology; colors the keypoint dots by
            segment color and adds the skeleton edge object.
        run_blender: Build the .blend now via `blender --background` when
            Blender is on PATH. The script is always written either way.

    Returns:
        Path to the generated scene script.
    """
    output_path = Path(output_path)
    frames, keypoint_ids, positions = _keypoint_trajectories(world_points)
    group_specs, edges = _color_groups(keypoint_ids, wireframe)

    groups_payload = [
        {
            "name": spec["name"],
            "color": spec["color"],
            "positions": np.round(positions[:, spec["columns"]], 5).tolist(),
        }
        for spec in group_specs
    ]

    cameras_payload = []
    videos = {} if videos is None else videos
    for cam_id in sorted(camera_array.posed_cameras):
        camera = camera_array.cameras[cam_id]
        assert camera.rotation is not None and camera.translation is not None and camera.matrix is not None
        fx, fy = float(camera.matrix[0, 0]), float(camera.matrix[1, 1])
        video = videos.get(cam_id)
        cameras_payload.append(
            {
                "name": f"cam_{cam_id}",
                "width": camera.size[0],
                "height": camera.size[1],
                "focal_px": (fx + fy) / 2.0,
                "matrix": _blender_camera_matrix(camera.rotation, camera.translation).tolist(),
                "video": str(Path(video).resolve()) if video is not None else None,
            }
        )
    if not cameras_payload:
        raise ValueError("CameraArray has no posed cameras to export.")

    payload = {
        "frames": frames,
        "groups": groups_payload,
        "joints": np.round(positions, 5).tolist() if edges else [],
        "edges": edges,
        "cameras": cameras_payload,
        "keypoint_radius_m": KEYPOINT_RADIUS_M,
        "floor_size_m": FLOOR_SIZE_M,
    }
    script = _SCENE_TEMPLATE.format(
        script_name=output_path.name,
        blend_name=output_path.with_suffix(".blend").name,
        payload_json=json.dumps(payload),
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(script)
    logger.info(f"Wrote Blender scene script: {output_path}")

    blender = shutil.which("blender")
    if run_blender and blender is not None:
        blend_path = output_path.with_suffix(".blend")
        blend_path.unlink(missing_ok=True)
        subprocess.run([blender, "--background", "--python", str(output_path)], check=True)
        # Blender exits 0 even when the scene script raises; the .blend is the proof.
        if not blend_path.exists():
            raise RuntimeError(f"Blender ran but did not produce {blend_path}; check its output above.")
    elif run_blender:
        logger.warning(f"Blender not on PATH; build manually: blender --background --python {output_path}")
    return output_path
