"""Tests for FrameSource.next_frame — forward-only decode correctness.

Why this matters: FrameSource assigns each frame a decode-order index via
enumerate. That index is the key the entire calibration pipeline uses to
align frames across cameras (via SynchronizedTimestamps). If the index is
wrong — off by one, skipping B-frames, or drifting under fractional fps —
the pipeline silently matches the wrong frames across cameras and the
calibration is corrupted with no visible error.

The first test (no ffmpeg needed) confirms the index space is contiguous
0..N-1 and matches the container's metadata frame count. The second test
(requires ffmpeg CLI) validates against an independent decoder: for each
requested frame, the argmin-SAD check proves that PyAV's frame at index i
is closer to ffmpeg's frame i than to its neighbors. An off-by-one cannot
satisfy this unless adjacent frames are pixel-identical (in which case the
substitution is harmless).

The fixture is a synthetic H.264 / B-frame / 59.94fps clip — the same
codec family as field data — generated by make_fixtures.py so it's
license-free and reproducible. B-frames and fractional rate are what make
decode-order indexing non-trivial; the repo's other test videos are
MPEG-4/no-B-frame/integer-rate and would pass vacuously.

The ffmpeg oracle test skips in CI (ffmpeg not installed) but runs locally.
The invariant it checks is stable — it only breaks if PyAV changes its
decode ordering or the fixture is regenerated.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np

from caliscope.recording.frame_source import FrameSource
from tests.oracle_ffmpeg import dump_frame, requires_ffmpeg

CLIP_DIR = Path(__file__).parent / "sessions" / "h264_extrinsic"
CLIP = CLIP_DIR / "cam_0.mp4"
N_FRAMES = 180  # verified via ffprobe nb_frames


def _sad(a: np.ndarray, b: np.ndarray) -> int:
    """Sum of absolute differences — pixel-level frame distance."""
    return int(np.abs(a.astype(np.int32) - b.astype(np.int32)).sum())


def test_next_frame_decode_count_matches_metadata():
    """Decode-order indices are contiguous 0..N-1, matching the metadata frame count."""
    fs = FrameSource.from_path(CLIP, cam_id=0)
    try:
        indices = []
        while (result := fs.next_frame()) is not None:
            indices.append(result.frame_index)
    finally:
        fs.close()
    assert indices == list(range(N_FRAMES))


@requires_ffmpeg
def test_next_frame_with_wanted_selects_true_frame():
    """Each frame returned by next_frame matches the same index decoded by ffmpeg.

    Argmin-SAD: the returned frame must be at least as close to ffmpeg's frame i
    as to ffmpeg's frame i-1 or i+1. This catches off-by-one indexing that would
    silently corrupt cross-camera alignment.
    """
    wanted = {0, 13, 60, 120, 170}
    fs = FrameSource.from_path(CLIP, cam_id=0, wanted_indices=wanted)
    try:
        got: dict[int, np.ndarray] = {}
        while (result := fs.next_frame()) is not None:
            got[result.frame_index] = result.frame
    finally:
        fs.close()

    assert set(got) == wanted
    for i in wanted:
        d_self = _sad(got[i], dump_frame(CLIP, i))
        for j in (i - 1, i + 1):
            if 0 <= j < N_FRAMES:
                assert _sad(got[i], dump_frame(CLIP, j)) >= d_self, f"frame {i} matches neighbor {j} better than itself"
